extproc perl -S
#!i:/perllib/bin/perl
    eval 'exec i:/perllib/bin/perl -S $0 ${1+"$@"}'
	if 0;

# This "perldoc" file was generated by "perldoc.PL"

require 5;
BEGIN { $^W = 1 if $ENV{'PERLDOCDEBUG'} }
use Pod::Perldoc;
exit( Pod::Perldoc->run() );

